spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

    jpa:
        database: H2
    
    datasource:
        url: jdbc:h2:mem:mydb2
        username: sa
        password: 
        driverClassName: org.h2.Driver
